#天码溯源平台
ifast:
  projectName: sypt-wx
  projectRootURL: http://c.tm315.top/

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.49.178:3306/sypt?characterEncoding=utf-8
    username: tianma315
    password: Tianmakeji315
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  social:
    wechat:
      app-id: wx11bcd47e4dc4e200
      app-secret: 5875b3b95b38519e1f0513053f167c02
      redirect-url: http://c.tm315.top/sypt_wx/open/{CODE},http://c.tm315.top/sypt_wx/open/{IDENT}/{CODE}

logging:
  file: /logs/sypt/sypt_wx.log
  level:
    root: info
    org:
      springframework:
        web: info
        security: debug
    com:
      tianma315: debug