server:
  port: 8088
  context-path: /sypt_wx
spring:
  profiles:
        active: dev
    #    active: test
#        active: local
#    active: prod
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
  social:
    wechat:
#      app-id: wx2907aeb92ae661f0
#      app-secret: 5f6aefb3498df80e11205bfed31f73cd
      #测试
      app-id: wx91d2600876d6adb4
      app-secret: c3bc80174a1981824b7acf612d2df6f7
#      app-id: wx11bcd47e4dc4e200
#      app-secret: acd47c763b82671eb9d8b243db7e2fb4

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys=true: true
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.tianma315.**.domain

security:
  basic:
    enabled: false
